config/routes.rb
Rails.application.routes.draw do
  resources :flips
  resources :investment_properties
  resources :inv_properties
  resources :myproperties
  resources :properties
  resources :items
  resources :expenses
  devise_for :users
  #devise_for :installs
  resources :workouts
  resources :expenses
  resources :inventory
  resources :friends
  #get 'home/index'
  get 'home/about'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/expense.rb
class Expense < ApplicationRecord
end

app/models/flip.rb
class Flip < ApplicationRecord
end

app/models/imageuser.rb
class Imageuser < ApplicationRecord
  has_one_attached :avatar
end

app/models/install.rb
class Install < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/inv_property.rb
class InvProperty < ApplicationRecord
end

app/models/investment_property.rb
class InvestmentProperty < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/myproperty.rb
class Myproperty < ApplicationRecord
end

app/models/property.rb
class Property < ApplicationRecord
end

app/models/session.rb
class Session < ApplicationRecord
end

app/models/studysession.rb
class Studysession < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/workout.rb
class Workout < ApplicationRecord
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :set_workout, only: %i[ show edit update destroy ]

  # GET /workouts or /workouts.json
  def index
    @workouts = Workout.order(params[:sort])
  end

  # GET /workouts/1 or /workouts/1.json
  def show
  end

  # GET /workouts/new
  def new
    @workout = Workout.new
  end

  # GET /workouts/1/edit
  def edit
  end

  # POST /workouts or /workouts.json
  def create
    @workout = Workout.new(workout_params)

    respond_to do |format|
      if @workout.save
        format.html { redirect_to @workout, notice: "Activity was successfully created." }
        format.json { render :show, status: :created, location: @workout }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workouts/1 or /workouts/1.json
  def update
    respond_to do |format|
      if @workout.update(workout_params)
        format.html { redirect_to @workout, notice: "Activity was successfully updated." }
        format.json { render :show, status: :ok, location: @workout }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workouts/1 or /workouts/1.json
  def destroy
    @workout.destroy
    respond_to do |format|
      format.html { redirect_to workouts_url, notice: "Activity was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workout
      @workout = Workout.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def workout_params
      params.require(:workout).permit(:day, :workout_name, :workout_type, :location, :time, :intensity)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/flips_helper.rb
module FlipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/workouts/_form.html.erb
<%= form_with(model: workout) do |form| %>
  <% if workout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(workout.errors.count, "error") %> prohibited this workout from being saved:</h2>

      <ul>
        <% workout.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

 <div class="field">
    <%= form.text_field :day, class: "form-control", placeholder:"Date (MM-DD-YYYY)" %>
  </div>
  <br>

 <div class="field">
    <%= form.text_field :workout_name, class: "form-control", placeholder:"Subject" %>
  </div>
    <br>
      <div class="field">
    <%= form.text_field :workout_type, class: "form-control", placeholder:"Category" %>
  </div>
    <br>
      <div class="field">
    <%= form.text_field :location, class: "form-control", placeholder:"Location" %>
  </div>
    <br>
      <div class="field">
    <%= form.text_field :time, class: "form-control", placeholder:"Duration (min)" %>
  </div>
    <br>
      <div class="field">
    <%= form.text_field :intensity, class: "form-control", placeholder:"Intensity (1-10)" %>
  </div>
    <br>

  <div class="actions">
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/workouts/edit.html.erb
<h1>Edit Activity</h1>

<%= render 'form', workout: @workout %>
<br>
<%= link_to 'Show', @workout, class:"btn btn-dark" %>
<%= link_to 'Back', workouts_path, class:"btn btn-secondary" %>

app/views/workouts/index.html.erb
<h2>Past Activities</h2>
<table class="table">
  <thead>
    <tr>
    <th><%= link_to "Date", :sort => "day"%> </th>
    <th><%= link_to "Subject", :sort => "workout_name"%> </th>
    <th><%= link_to "Category", :sort => "workout_type"%> </th>
    <th><%= link_to "Location", :sort => "location"%> </th>
    <th><%= link_to "Intensity", :sort => "intensity"%> </th>
    <th><%= link_to "Duration (min)", :sort => "time"%> </th>
    <th><%= form_tag(workouts_path, method: :get) do %></th>
  <th><%= text_field_tag(:search, params[:search]) %> </th>
  <th><%= submit_tag ("Search"), class:"btn btn-dark" %></th>
  <br>
<% end %>
      <th colspan="3"></th>
      <% @workouts.each do |workout| %>
  <% end %>
    </tr>
  </thead>
  <tbody>
    <% @workouts.each do |workout| %>
      <tr>
  <tr>
    <td><%= workout.day %></td>
    <td><%= workout.workout_name %></td>
    <td><%= workout.workout_type %></td>
    <td><%= workout.location %></td>
    <td><%= workout.intensity %></td>
    <td><%= workout.time %></td>    

    <td><%= link_to 'Show', workout, class:"btn btn-primary btn-sm" %></td>
    <td><%= link_to 'Edit', edit_workout_path(workout), class:"btn btn-dark btn-sm" %></td>
    <td><%= link_to 'Delete', workout, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger btn-sm" %></td>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Activity', new_workout_path, class:"btn btn-dark" %>
<br>
<br>
<br>
<br>
<br>
<br>

<h2>Activity Summary</h2>
<br>
<br>
<%= bar_chart Workout.group(:workout_type).sum(:time) %>
<br>
<p class="text-center">Minutes</p>

app/views/workouts/new.html.erb
<h3>New Activity</h3>
<br/>

<%= render 'form', workout: @workout, class:"btn btn-primary" %>
<br/>

<%= link_to 'Back', workouts_path, class:"btn btn-dark" %>

app/views/workouts/show.html.erb
<p>
  <strong>Date:</strong>
  <%= @workout.day %>
</p>

<p>
  <strong>Activity Name:</strong>
  <%= @workout.workout_name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @workout.workout_type %>
</p>

<p>
  <strong>Location:</strong>
  <%= @workout.location %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @workout.time %>
</p>

<p>
  <strong>Intensity:</strong>
  <%= @workout.intensity %>
</p>

<%= link_to 'Edit', edit_workout_path(@workout), class:"btn btn-dark" %>
<%= link_to 'Back', workouts_path, class:"btn btn-secondary" %>