config/routes.rb
Rails.application.routes.draw do
  resources :flips
  resources :investment_properties
  resources :inv_properties
  resources :myproperties
  resources :properties
  resources :items
  resources :expenses
  devise_for :users
  #devise_for :installs
  resources :workouts
  resources :expenses
  resources :inventory
  resources :friends
  #get 'home/index'
  get 'home/about'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/expense.rb
class Expense < ApplicationRecord
end

app/models/flip.rb
class Flip < ApplicationRecord
end

app/models/imageuser.rb
class Imageuser < ApplicationRecord
  has_one_attached :avatar
end

app/models/install.rb
class Install < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/inv_property.rb
class InvProperty < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/myproperty.rb
class Myproperty < ApplicationRecord
end

app/models/property.rb
class Property < ApplicationRecord
end

app/models/session.rb
class Session < ApplicationRecord
end

app/models/studysession.rb
class Studysession < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/workout.rb
class Workout < ApplicationRecord
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

    def about
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/flips_helper.rb
module FlipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <%= link_to 'Upside', root_path, class: "navbar-brand" %> 
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <% if user_signed_in? %>

        <li class="nav-item">
            <%= link_to "Time", new_workout_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
          <%= link_to "Expenses", expenses_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to "Inventory", items_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
      <%= link_to "My Properties", flips_path, class: "nav-link" %>
    </li>
                  <li class="nav-item">
          <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %>
         </li> 
                  <li class="nav-item">
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
         </li>

      <% else %>

        <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          </li>
          
        <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
          </li>
      <% end %>
                

    </div>
    </ul>
  </div>
</nav>

app/views/home/index.html.erb
<h2>Dashboard</h2>
<p>Keep track of your activities.</p>
<p>Quick Add</p>

        <%= link_to "Expense", new_expense_path, class:"btn btn-dark" %>
        <%= link_to "Item", new_item_path, class:"btn btn-dark" %>
        <%= link_to "Mileage", new_item_path, class:"btn btn-dark" %>