config/routes.rb
Rails.application.routes.draw do
  resources :flips
  resources :investment_properties
  resources :inv_properties
  resources :myproperties
  resources :properties
  resources :items
  resources :expenses
  devise_for :users
  #devise_for :installs
  resources :workouts
  resources :expenses
  resources :inventory
  resources :friends
  #get 'home/index'
  get 'home/about'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/expense.rb
class Expense < ApplicationRecord
end

app/models/flip.rb
class Flip < ApplicationRecord
end

app/models/imageuser.rb
class Imageuser < ApplicationRecord
  has_one_attached :avatar
end

app/models/install.rb
class Install < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/inv_property.rb
class InvProperty < ApplicationRecord
end

app/models/investment_property.rb
class InvestmentProperty < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/myproperty.rb
class Myproperty < ApplicationRecord
end

app/models/property.rb
class Property < ApplicationRecord
end

app/models/session.rb
class Session < ApplicationRecord
end

app/models/studysession.rb
class Studysession < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/workout.rb
class Workout < ApplicationRecord
end

app/controllers/flips_controller.rb
class FlipsController < ApplicationController
  before_action :set_flip, only: %i[ show edit update destroy ]

  # GET /flips or /flips.json
  def index
    @flips = Flip.all
  end

  # GET /flips/1 or /flips/1.json
  def show
  end

  # GET /flips/new
  def new
    @flip = Flip.new
  end

  # GET /flips/1/edit
  def edit
  end

  # POST /flips or /flips.json
  def create
    @flip = Flip.new(flip_params)

    respond_to do |format|
      if @flip.save
        format.html { redirect_to @flip, notice: "Flip was successfully created." }
        format.json { render :show, status: :created, location: @flip }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @flip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flips/1 or /flips/1.json
  def update
    respond_to do |format|
      if @flip.update(flip_params)
        format.html { redirect_to @flip, notice: "Flip was successfully updated." }
        format.json { render :show, status: :ok, location: @flip }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @flip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flips/1 or /flips/1.json
  def destroy
    @flip.destroy
    respond_to do |format|
      format.html { redirect_to flips_url, notice: "Flip was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flip
      @flip = Flip.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def flip_params
      params.require(:flip).permit(:date, :address_one, :address_two, :address_city, :address_state, :address_county, :status, :beds, :baths, :square_foot, :overview, :feature_one, :feature_two, :feature_three, :home_value, :tax_history, :price_history, :monthly_cost, :nearby_schools, :legal_protections, :home_type, :year_built, :hoa_string, :price_per_square_foot, :flooring, :heating, :cooling, :lot_size, :lot_features_string, :foundation, :roof_type, :roof_age, :water_util, :electricity_util, :sewer_util, :association_name, :annual_taxes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/flips_helper.rb
module FlipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/flips/_form.html.erb
<%= form_with(model: flip) do |form| %>
  <% if flip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(flip.errors.count, "error") %> prohibited this flip from being saved:</h2>

      <ul>
        <% flip.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :address_one %>
    <%= form.text_field :address_one %>
  </div>

  <div class="field">
    <%= form.label :address_two %>
    <%= form.text_field :address_two %>
  </div>

  <div class="field">
    <%= form.label :address_city %>
    <%= form.text_field :address_city %>
  </div>

  <div class="field">
    <%= form.label :address_state %>
    <%= form.text_field :address_state %>
  </div>

  <div class="field">
    <%= form.label :address_county %>
    <%= form.text_field :address_county %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :beds %>
    <%= form.text_field :beds %>
  </div>

  <div class="field">
    <%= form.label :baths %>
    <%= form.text_field :baths %>
  </div>

  <div class="field">
    <%= form.label :square_foot %>
    <%= form.text_field :square_foot %>
  </div>

  <div class="field">
    <%= form.label :overview %>
    <%= form.text_field :overview %>
  </div>

  <div class="field">
    <%= form.label :feature_one %>
    <%= form.text_field :feature_one %>
  </div>

  <div class="field">
    <%= form.label :feature_two %>
    <%= form.text_field :feature_two %>
  </div>

  <div class="field">
    <%= form.label :feature_three %>
    <%= form.text_field :feature_three %>
  </div>

  <div class="field">
    <%= form.label :home_value %>
    <%= form.text_field :home_value %>
  </div>

  <div class="field">
    <%= form.label :tax_history %>
    <%= form.text_field :tax_history %>
  </div>

  <div class="field">
    <%= form.label :price_history %>
    <%= form.text_field :price_history %>
  </div>

  <div class="field">
    <%= form.label :monthly_cost %>
    <%= form.text_field :monthly_cost %>
  </div>

  <div class="field">
    <%= form.label :nearby_schools %>
    <%= form.text_field :nearby_schools %>
  </div>

  <div class="field">
    <%= form.label :legal_protections %>
    <%= form.text_field :legal_protections %>
  </div>

  <div class="field">
    <%= form.label :home_type %>
    <%= form.text_field :home_type %>
  </div>

  <div class="field">
    <%= form.label :year_built %>
    <%= form.text_field :year_built %>
  </div>

  <div class="field">
    <%= form.label :hoa_string %>
    <%= form.text_field :hoa_string %>
  </div>

  <div class="field">
    <%= form.label :price_per_square_foot %>
    <%= form.text_field :price_per_square_foot %>
  </div>

  <div class="field">
    <%= form.label :flooring %>
    <%= form.text_field :flooring %>
  </div>

  <div class="field">
    <%= form.label :heating %>
    <%= form.text_field :heating %>
  </div>

  <div class="field">
    <%= form.label :cooling %>
    <%= form.text_field :cooling %>
  </div>

  <div class="field">
    <%= form.label :lot_size %>
    <%= form.text_field :lot_size %>
  </div>

  <div class="field">
    <%= form.label :lot_features_string %>
    <%= form.text_field :lot_features_string %>
  </div>

  <div class="field">
    <%= form.label :foundation %>
    <%= form.text_field :foundation %>
  </div>

  <div class="field">
    <%= form.label :roof_type %>
    <%= form.text_field :roof_type %>
  </div>

  <div class="field">
    <%= form.label :roof_age %>
    <%= form.text_field :roof_age %>
  </div>

  <div class="field">
    <%= form.label :water_util %>
    <%= form.text_field :water_util %>
  </div>

  <div class="field">
    <%= form.label :electricity_util %>
    <%= form.text_field :electricity_util %>
  </div>

  <div class="field">
    <%= form.label :sewer_util %>
    <%= form.text_field :sewer_util %>
  </div>

  <div class="field">
    <%= form.label :association_name %>
    <%= form.text_field :association_name %>
  </div>

  <div class="field">
    <%= form.label :annual_taxes %>
    <%= form.text_field :annual_taxes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/flips/edit.html.erb
<h1>Editing Flip</h1>

<%= render 'form', flip: @flip %>

<%= link_to 'Show', @flip %> |
<%= link_to 'Back', flips_path %>

app/views/flips/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Flips</h1>

<table class"table">
  <thead>
    <tr>
      <th>Date</th>
      <th>Address one</th>
            <th>Address city</th>
      <th>Address state</th>
      <th>Address county</th>
      <th>Status</th>
      <th>Beds</th>
      <th>Baths</th>
      <th>Square foot</th>
      <th>Year built</th>
      <th>Price per square foot</th>
      <th>Lot size</th>
      <th>Foundation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @flips.each do |flip| %>
      <tr>
        <td><%= flip.date %></td>
        <td><%= flip.address_one %></td>
        <td><%= flip.address_city %></td>
        <td><%= flip.address_state %></td>
        <td><%= flip.address_county %></td>
        <td><%= flip.status %></td>
        <td><%= flip.baths %></td>
        <td><%= flip.square_foot %></td>
        <td><%= flip.overview %></td>
        <td><%= flip.year_built %></td>
        <td><%= flip.price_per_square_foot %></td>
        <td><%= flip.lot_size %></td>
        <td><%= flip.foundation %></td>

        <td><%= link_to 'Show', flip %></td>
        <td><%= link_to 'Edit', edit_flip_path(flip) %></td>
        <td><%= link_to 'Destroy', flip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Flip', new_flip_path %>

app/views/flips/new.html.erb
<h1>New Flip</h1>

<%= render 'form', flip: @flip %>

<%= link_to 'Back', flips_path %>

app/views/flips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @flip.date %>
</p>

<p>
  <strong>Address one:</strong>
  <%= @flip.address_one %>
</p>

<p>
  <strong>Address two:</strong>
  <%= @flip.address_two %>
</p>

<p>
  <strong>Address city:</strong>
  <%= @flip.address_city %>
</p>

<p>
  <strong>Address state:</strong>
  <%= @flip.address_state %>
</p>

<p>
  <strong>Address county:</strong>
  <%= @flip.address_county %>
</p>

<p>
  <strong>Status:</strong>
  <%= @flip.status %>
</p>

<p>
  <strong>Beds:</strong>
  <%= @flip.beds %>
</p>

<p>
  <strong>Baths:</strong>
  <%= @flip.baths %>
</p>

<p>
  <strong>Square foot:</strong>
  <%= @flip.square_foot %>
</p>

<p>
  <strong>Overview:</strong>
  <%= @flip.overview %>
</p>

<p>
  <strong>Feature one:</strong>
  <%= @flip.feature_one %>
</p>

<p>
  <strong>Feature two:</strong>
  <%= @flip.feature_two %>
</p>

<p>
  <strong>Feature three:</strong>
  <%= @flip.feature_three %>
</p>

<p>
  <strong>Home value:</strong>
  <%= @flip.home_value %>
</p>

<p>
  <strong>Tax history:</strong>
  <%= @flip.tax_history %>
</p>

<p>
  <strong>Price history:</strong>
  <%= @flip.price_history %>
</p>

<p>
  <strong>Monthly cost:</strong>
  <%= @flip.monthly_cost %>
</p>

<p>
  <strong>Nearby schools:</strong>
  <%= @flip.nearby_schools %>
</p>

<p>
  <strong>Legal protections:</strong>
  <%= @flip.legal_protections %>
</p>

<p>
  <strong>Home type:</strong>
  <%= @flip.home_type %>
</p>

<p>
  <strong>Year built:</strong>
  <%= @flip.year_built %>
</p>

<p>
  <strong>Hoa string:</strong>
  <%= @flip.hoa_string %>
</p>

<p>
  <strong>Price per square foot:</strong>
  <%= @flip.price_per_square_foot %>
</p>

<p>
  <strong>Flooring:</strong>
  <%= @flip.flooring %>
</p>

<p>
  <strong>Heating:</strong>
  <%= @flip.heating %>
</p>

<p>
  <strong>Cooling:</strong>
  <%= @flip.cooling %>
</p>

<p>
  <strong>Lot size:</strong>
  <%= @flip.lot_size %>
</p>

<p>
  <strong>Lot features string:</strong>
  <%= @flip.lot_features_string %>
</p>

<p>
  <strong>Foundation:</strong>
  <%= @flip.foundation %>
</p>

<p>
  <strong>Roof type:</strong>
  <%= @flip.roof_type %>
</p>

<p>
  <strong>Roof age:</strong>
  <%= @flip.roof_age %>
</p>

<p>
  <strong>Water util:</strong>
  <%= @flip.water_util %>
</p>

<p>
  <strong>Electricity util:</strong>
  <%= @flip.electricity_util %>
</p>

<p>
  <strong>Sewer util:</strong>
  <%= @flip.sewer_util %>
</p>

<p>
  <strong>Association name:</strong>
  <%= @flip.association_name %>
</p>

<p>
  <strong>Annual taxes:</strong>
  <%= @flip.annual_taxes %>
</p>

<%= link_to 'Edit', edit_flip_path(@flip) %> |
<%= link_to 'Back', flips_path %>